services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t client ./client

script:
  - docker run client npm run test

after_install:
  - docker build -t jblanch94/reviewy-client ./client
  - docker build -t jblanch94/reviewy-api ./server
  - docker build -t jblanch94/reviewy-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jblanch94/reviewy-client
  - docker push jblanch94/reviewy-api
  - docker push jblanch94/reviewy-nginx
