services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t jblanch94/client-test ./client

script:
  - docker run -e CI=true jblanch94/client-test npm test

after_install:
  - docker build -t jblanch94/reviewy-client ./client
  - docker build -t jblanch94/reviewy-api ./server
  - docker build -t jblanch94/reviewy-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jblanch94/reviewy-client
  - docker push jblanch94/reviewy-api
  - docker push jblanch94/reviewy-nginx
