version: '3.8'

services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app/
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app/
    env_file: 
      - ./server/src/.env
    volumes:
      - ./server/src/db/:/docker-entrypoint-initdb.d/
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
    restart: always
    depends_on: 
      - client
