export default {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT: "LOGOUT",
  ERROR: "ERROR",
  FETCH_USER: "FETCH_USER",
  UPDATE_USER: "UPDATE_USER",
  FETCH_RESTAURANTS: "FETCH_RESTAURANTS",
  FETCH_RESTAURANT_REVIEWS: "FETCH_RESTAURANT_REVIEWS",
};
