export default {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT: 'LOGOUT',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  ERROR: 'ERROR',
  FETCH_USER: 'FETCH_USER',
  UPDATE_USER: 'UPDATE_USER',
  FETCH_RESTAURANTS: 'FETCH_RESTAURANTS',
  FETCH_RESTAURANT_REVIEWS: 'FETCH_RESTAURANT_REVIEWS',
  SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  ADD_RESTAURANT: 'ADD_RESTAURANT',
  FETCH_USER_BY_ID: 'FETCH_USER_BY_ID'
};
